//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TD.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TD.Common.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong; the branch could not be created..
        /// </summary>
        internal static string AddBranchError {
            get {
                return ResourceManager.GetString("AddBranchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong; the customer could not be created..
        /// </summary>
        internal static string AddCustomerError {
            get {
                return ResourceManager.GetString("AddCustomerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong; the employee could not be created..
        /// </summary>
        internal static string AddEmployeeError {
            get {
                return ResourceManager.GetString("AddEmployeeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong; the family could not be created..
        /// </summary>
        internal static string AddFamilyError {
            get {
                return ResourceManager.GetString("AddFamilyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong; the franchise could not be created..
        /// </summary>
        internal static string AddFranchiseError {
            get {
                return ResourceManager.GetString("AddFranchiseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong; the product or service could not be created..
        /// </summary>
        internal static string AddProdServError {
            get {
                return ResourceManager.GetString("AddProdServError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch{0} has been added successfully..
        /// </summary>
        internal static string AddSuccessBranch {
            get {
                return ResourceManager.GetString("AddSuccessBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer {0} has been added successfully..
        /// </summary>
        internal static string AddSuccessClient {
            get {
                return ResourceManager.GetString("AddSuccessClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family {0} has been added successfully..
        /// </summary>
        internal static string AddSuccessFamily {
            get {
                return ResourceManager.GetString("AddSuccessFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Franchise {0} has been added successfully..
        /// </summary>
        internal static string AddSuccessFranchise {
            get {
                return ResourceManager.GetString("AddSuccessFranchise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product or Service {0} has been added successfully..
        /// </summary>
        internal static string AddSuccessProdServ {
            get {
                return ResourceManager.GetString("AddSuccessProdServ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} has been added successfully..
        /// </summary>
        internal static string AddSuccessUser {
            get {
                return ResourceManager.GetString("AddSuccessUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data been fetched successfully..
        /// </summary>
        internal static string GetSuccess {
            get {
                return ResourceManager.GetString("GetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Not Found..
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch {0} has been updated successfully..
        /// </summary>
        internal static string UpdateBranch {
            get {
                return ResourceManager.GetString("UpdateBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong; the branch could not be Updated..
        /// </summary>
        internal static string UpdateBranchError {
            get {
                return ResourceManager.GetString("UpdateBranchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer {0} has been updated successfully..
        /// </summary>
        internal static string UpdateCustomer {
            get {
                return ResourceManager.GetString("UpdateCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong; the customer could not be Updated..
        /// </summary>
        internal static string UpdateCustomerError {
            get {
                return ResourceManager.GetString("UpdateCustomerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee {0} has been updated successfully..
        /// </summary>
        internal static string UpdateEmployee {
            get {
                return ResourceManager.GetString("UpdateEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong; the employee could not be Updated..
        /// </summary>
        internal static string UpdateEmployeeError {
            get {
                return ResourceManager.GetString("UpdateEmployeeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong; the family could not be Updated..
        /// </summary>
        internal static string UpdateFamilyError {
            get {
                return ResourceManager.GetString("UpdateFamilyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Franchise {0} has been updated successfully..
        /// </summary>
        internal static string UpdateFranchise {
            get {
                return ResourceManager.GetString("UpdateFranchise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong; the franchise could not be Updated..
        /// </summary>
        internal static string UpdateFranchiseError {
            get {
                return ResourceManager.GetString("UpdateFranchiseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porduct or Service {0} has been updated successfully..
        /// </summary>
        internal static string UpdateProdServ {
            get {
                return ResourceManager.GetString("UpdateProdServ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong; the producto or service could not be Updated..
        /// </summary>
        internal static string UpdateProdServError {
            get {
                return ResourceManager.GetString("UpdateProdServError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitingList {0} has been updated successfully..
        /// </summary>
        internal static string UpdateWaitingList {
            get {
                return ResourceManager.GetString("UpdateWaitingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong; the WaitingList could not be Updated..
        /// </summary>
        internal static string UpdateWaitingListError {
            get {
                return ResourceManager.GetString("UpdateWaitingListError", resourceCulture);
            }
        }
    }
}
